# .streamlit/secrets.toml

private_gsheets_url = "https://docs.google.com/spreadsheets/d/1tuqOdo_xjfbIvZxhxAHfJTVrZatpu8XY-At3LfodWFc/edit?usp=sharing"
connection_url = "mongodb+srv://wchim:aUkvGgAarVb8Gv3P@hda-cluster.qtfcgsu.mongodb.net/sample_airbnb"

[gcp_service_account]
type = "service_account"
project_id = "hda-gsheet-connect"
private_key_id = "0e3f2b4e1012c08668933d971c4a307046487eab"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCdubqZQ3E6FRoZ\nK5lRWXm4QPf65wmvRlG/MF04Q+RBx4HqOdhxUMnzPLw4HpEtnfo5ni7CX+7CSpwI\nz5G2E4I2K8H/uwOX2IF4UBXYPsoNtev7xI12sz0w/7eKix9S1Gz40jDG72gut/Kp\nGLvvmR+cMSCo0+EWiiQYE9tsyJZJW/AFPp0rotj8H4d3ZBLhxz5wxC+fKpNMjsD+\nHMSRrZqjzousvFeLEmwk/Xxpv1uk+hgSKSywPLXGuwIZjZb+toNyQV1CoWruYhGn\nIga3/6azPvBlDkJQHaS4+lV8sNvzagzU30itWPbOSq4w3ymz+uSkm9LTQSMHrYZi\nCuFzhsf3AgMBAAECggEAPOS1y/Ijxr7a4pjYinW27pH2q2GDda36ZYvwkYZ0m4jA\n+YL3s1fzf/sU173FYw04zAHsH5MWBOD1ONmacec6QFvIfEjhbEBkS+TvahtjusNf\npkYOL6OnnkE7xTtNDpeAstfDiSpo2JCgGPS5qhk+APlemI+kuSUAJmOUNX2DuDIw\norhjdkwBxcqdYoIij8j0iUZY2QDdh4wP+mR0XkmXJbIogbT94ifJNNaxwcL2LxTR\np6UidHouW1jCcwn7URNQAQTC6bNc/pHRF7Pt9V/rYV76PCQVODFtjnb/ax0urcQA\nRU5jT3y0A21BBnQMnpmMnUtCl35NPivnYQjVVBg4MQKBgQDdpUmDK3iw5IYdMhPa\nKnOhEgKoT3qw3kF8ZSL+eMhKSAX9gfyzcBlKswr8K8OgZwaMaAdSdHuCol1wtQb6\nkvm8oDWoj4zIMmOGTsuxxAHx1XojVwTtkbXM5x4M81mLtc09p00HxgcxHkYS+I36\nigJXZ8yIOMpYIouhSim5xMG2dQKBgQC2LCTgOKCTCgRt11FYCqQrUfp4XSBZKz7N\n6VOh2Q2RcXujUINiOh54wVUVIXbTKPT5jyZ3FUfMWaeXdyNfTHzCusRgUAZXpBFT\nik8HvcLQO1/zc1pHm6zEk6vHp7VkAE/p77mLc+AdOarq83cDjL0rFik9V2ojTKVZ\nf7nqIxFvOwKBgQCQKgkVoznePNWqub7F4WTSOEe4N/IChp2rjpDjWaZVAmG7EUhP\nYjNhLfGQMdsNQtW0j5lrnU4Umw0R2P1QEDcV5FLib3RPZs7rNecxmd718DeAMwKG\nj4bjXtRh8gqlX7u+RUpKKxjUbu9/OWIHuqppNZ+IXv/lsZqGbxmSthKVXQKBgBTy\nnorp+AzwafH3gHMPRjF1C8grbTzTrDUhT2yc+OJwmjb9Wx5AcKCSGqaDYpaFbyYD\nP/kRiWAGLy9Lk9WxhecectZgXVpWk2d3z/6j43LuYOotqYPycrtn/6jFsCX/ozDT\nUBKpEGxL5Ut/E4Bk/pulwLg9BQdqGNlhxo8V2TthAoGAZSB0IQm0r9DnwwzkzFUI\nq9hhOHtBXLjyPnJFRUS4ZqZ4sGTgrXVrrtCKd+gPHDhQtF8bjX+owkT9WMyosoTC\n+ztsaT1xRm+1npEw0mSoefZebxicfmR4J5jvvOaeTSVWA22GArEhSjAJbO6OOHGv\nfyCfrOItoUa5sd1PRBJjeDI=\n-----END PRIVATE KEY-----\n"
client_email = "hda-service-acc@hda-gsheet-connect.iam.gserviceaccount.com"
client_id = "113601800016767334980"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/hda-service-acc%40hda-gsheet-connect.iam.gserviceaccount.com"

[mongo]
host = "localhost"
port = 27017
username = "wchim"
password = "aUkvGgAarVb8Gv3P"
